//LED PROGRAM
// Pins: D2-D13, A0-A2
void setup()
{
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
  pinMode(A0, OUTPUT);
  pinMode(A1, OUTPUT);
  pinMode(A2, OUTPUT);
}
void loop()
{
//All LEDs ON/OFF
  // All LEDs ON
    digitalWrite(2, HIGH);
    digitalWrite(3, HIGH);
    digitalWrite(4, HIGH);
    digitalWrite(5, HIGH);
    digitalWrite(6, HIGH);
    digitalWrite(7, HIGH);
    digitalWrite(8, HIGH);
    digitalWrite(9, HIGH);
    digitalWrite(10, HIGH);
    digitalWrite(11, HIGH);
    digitalWrite(12, HIGH);
    digitalWrite(13, HIGH);
    digitalWrite(A0, HIGH);
    digitalWrite(A1, HIGH);
    digitalWrite(A2, HIGH);
    delay(1000);
  // All LEDs OFF
    digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);
    digitalWrite(5, LOW);
    digitalWrite(6, LOW);
    digitalWrite(7, LOW);
    digitalWrite(8, LOW);
    digitalWrite(9, LOW);
    digitalWrite(10, LOW);
    digitalWrite(11, LOW);
    digitalWrite(12, LOW);
    digitalWrite(13, LOW);
    digitalWrite(A0, LOW);
    digitalWrite(A1, LOW);
    digitalWrite(A2, LOW);
    delay(1000);
//Running Light Left to Right
  digitalWrite(2, HIGH);
  delay(200);
  digitalWrite(2, LOW);
  digitalWrite(3, HIGH);
  delay(200);
  digitalWrite(3, LOW);
  digitalWrite(4, HIGH);
  delay(200);
  digitalWrite(4, LOW);
  digitalWrite(5, HIGH);
  delay(200);
  digitalWrite(5, LOW);
  digitalWrite(6, HIGH);
  delay(200);
  digitalWrite(6, LOW);
  digitalWrite(7, HIGH);
  delay(200);
  digitalWrite(7, LOW);
  digitalWrite(8, HIGH);
  delay(200);
  digitalWrite(8, LOW);
  digitalWrite(9, HIGH);
  delay(200);
  digitalWrite(9, LOW);
  digitalWrite(10, HIGH);
  delay(200);
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  delay(200);
  digitalWrite(11, LOW);
  digitalWrite(12, HIGH);
  delay(200);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(200);
  digitalWrite(13, LOW);
  digitalWrite(A0, HIGH);
  delay(200);
  digitalWrite(A0, LOW);
  digitalWrite(A1, HIGH);
  delay(200);
  digitalWrite(A1, LOW);
  digitalWrite(A2, HIGH);
  delay(100);
  digitalWrite(A2, LOW);
//Running Light Right to Left
    digitalWrite(A2, HIGH);
    delay(200);
    digitalWrite(A2, LOW);
    digitalWrite(A1, HIGH);
    delay(200);
    digitalWrite(A1, LOW);
    digitalWrite(A0, HIGH);
    delay(200);
    digitalWrite(A0, LOW);
    digitalWrite(13, HIGH);
    delay(200);
    digitalWrite(13, LOW);
    digitalWrite(12, HIGH);
    delay(200);
    digitalWrite(12, LOW);
    digitalWrite(11, HIGH);
    delay(200);
    digitalWrite(11, LOW);
    digitalWrite(10, HIGH);
    delay(200);
    digitalWrite(10, LOW);
    digitalWrite(9, HIGH);
    delay(200);
    digitalWrite(9, LOW);
    digitalWrite(8, HIGH);
    delay(200);
    digitalWrite(8, LOW);
    digitalWrite(7, HIGH);
    delay(200);
    digitalWrite(7, LOW);
    digitalWrite(6, HIGH);
    delay(200);
    digitalWrite(6, LOW);
    digitalWrite(5, HIGH);
    delay(200);
    digitalWrite(5, LOW);
    digitalWrite(4, HIGH);
    delay(200);
    digitalWrite(4, LOW);
    digitalWrite(3, HIGH);
    delay(200);
    digitalWrite(3, LOW);
    digitalWrite(2, HIGH);
    delay(200);
    digitalWrite(2, LOW);
//Fill Up Effect
    digitalWrite(2, HIGH);
    delay(200);
    digitalWrite(3, HIGH);
    delay(200);
    digitalWrite(4, HIGH);
    delay(200);
    digitalWrite(5, HIGH);
    delay(200);
    digitalWrite(6, HIGH);
    delay(200);
    digitalWrite(7, HIGH);
    delay(200);
    digitalWrite(8, HIGH);
    delay(200);
    digitalWrite(9, HIGH);
    delay(200);
    digitalWrite(10, HIGH);
    delay(200);
    digitalWrite(11, HIGH);
    delay(200);
    digitalWrite(12, HIGH);
    delay(200);
    digitalWrite(13, HIGH);
    delay(200);
    digitalWrite(A0, HIGH);
    delay(200);
    digitalWrite(A1, HIGH);
    delay(200);
    digitalWrite(A2, HIGH);
    delay(1000);
    digitalWrite(2, LOW);
    digitalWrite(3, LOW);
    digitalWrite(4, LOW);
    digitalWrite(5, LOW);
    digitalWrite(6, LOW);
    digitalWrite(7, LOW);
    digitalWrite(8, LOW);
    digitalWrite(9, LOW);
    digitalWrite(10, LOW);
    digitalWrite(11, LOW);
    digitalWrite(12, LOW);
    digitalWrite(13, LOW);
    digitalWrite(A0, LOW);
    digitalWrite(A1, LOW);
    digitalWrite(A2, LOW);
    delay(500);
//Empty Down Effect
digitalWrite(2, HIGH);
digitalWrite(3, HIGH);
digitalWrite(4, HIGH);
digitalWrite(5, HIGH);
digitalWrite(6, HIGH);
digitalWrite(7, HIGH);
digitalWrite(8, HIGH);
digitalWrite(9, HIGH);
digitalWrite(10, HIGH);
digitalWrite(11, HIGH);
digitalWrite(12, HIGH);
digitalWrite(13, HIGH);
digitalWrite(A0, HIGH);
digitalWrite(A1, HIGH);
digitalWrite(A2, HIGH);
delay(1000);
digitalWrite(A2, LOW);
delay(200);
digitalWrite(A1, LOW);
delay(200);
digitalWrite(A0, LOW);
delay(200);
digitalWrite(13, LOW);
delay(200);
digitalWrite(12, LOW);
delay(200);
digitalWrite(11, LOW);
delay(200);
digitalWrite(10, LOW);
delay(200);
digitalWrite(9, LOW);
delay(200);
digitalWrite(8, LOW);
delay(200);
digitalWrite(7, LOW);
delay(200);
digitalWrite(6, LOW);
delay(200);
digitalWrite(5, LOW);
delay(200);
digitalWrite(4, LOW);
delay(200);
digitalWrite(3, LOW);
delay(200);
digitalWrite(2, LOW);
delay(500);
//Alternate LEDs Blink
digitalWrite(2, HIGH);
digitalWrite(4, HIGH);
digitalWrite(6, HIGH);
digitalWrite(8, HIGH);
digitalWrite(10, HIGH);
digitalWrite(12, HIGH);
digitalWrite(A0, HIGH);
digitalWrite(A2, HIGH);
digitalWrite(3, LOW);
digitalWrite(5, LOW);
digitalWrite(7, LOW);
digitalWrite(9, LOW);
digitalWrite(11, LOW);
digitalWrite(13, LOW);
digitalWrite(A1, LOW);
delay(500);
digitalWrite(2, LOW);
digitalWrite(4, LOW);
digitalWrite(6, LOW);
digitalWrite(8, LOW);
digitalWrite(10, LOW);
digitalWrite(12, LOW);
digitalWrite(A0, LOW);
digitalWrite(A2, LOW);
digitalWrite(3, HIGH);
digitalWrite(5, HIGH);
digitalWrite(7, HIGH);
digitalWrite(9, HIGH);
digitalWrite(11, HIGH);
digitalWrite(13, HIGH);
digitalWrite(A1, HIGH);
delay(500);   
//Odd LEDs ON / Even LEDs OFF
digitalWrite(2, LOW);
digitalWrite(3, HIGH);
digitalWrite(4, LOW);
digitalWrite(5, HIGH);
digitalWrite(6, LOW);
digitalWrite(7, HIGH);
digitalWrite(8, LOW);
digitalWrite(9, HIGH);
digitalWrite(10, LOW);
digitalWrite(11, HIGH);
digitalWrite(12, LOW);
digitalWrite(13, HIGH);
digitalWrite(A0, LOW);
digitalWrite(A1, HIGH);
digitalWrite(A2, LOW);
delay(500);
digitalWrite(2, HIGH);
digitalWrite(3, LOW);
digitalWrite(4, HIGH);
digitalWrite(5, LOW);
digitalWrite(6, HIGH);
digitalWrite(7, LOW);
digitalWrite(8, HIGH);
digitalWrite(9, LOW);
digitalWrite(10, HIGH);
digitalWrite(11, LOW);
digitalWrite(12, HIGH);
digitalWrite(13, LOW);
digitalWrite(A0, HIGH);
digitalWrite(A1, LOW);
digitalWrite(A2, HIGH);
delay(500);  
//Bounce Effect
digitalWrite(2, HIGH);
delay(150);
digitalWrite(2, LOW);
digitalWrite(3, HIGH);
delay(150);
digitalWrite(3, LOW);
digitalWrite(4, HIGH);
delay(150);
digitalWrite(4, LOW);
digitalWrite(5, HIGH);
delay(150);
digitalWrite(5, LOW);
digitalWrite(6, HIGH);
delay(150);
digitalWrite(6, LOW);
digitalWrite(7, HIGH);
delay(150);
digitalWrite(7, LOW);
digitalWrite(8, HIGH);
delay(150);
digitalWrite(8, LOW);
digitalWrite(9, HIGH);
delay(150);
digitalWrite(9, LOW);
digitalWrite(10, HIGH);
delay(150);
digitalWrite(10, LOW);
digitalWrite(11, HIGH);
delay(150);
digitalWrite(11, LOW);
digitalWrite(12, HIGH);
delay(150);
digitalWrite(12, LOW);
digitalWrite(13, HIGH);
delay(150);
digitalWrite(13, LOW);
digitalWrite(A0, HIGH);
delay(150);
digitalWrite(A0, LOW);
digitalWrite(A1, HIGH);
delay(150);
digitalWrite(A1, LOW);
digitalWrite(A2, HIGH);
delay(150);
digitalWrite(A2, LOW);
//Reverse
digitalWrite(A1, HIGH);
delay(150);
digitalWrite(A1, LOW);
digitalWrite(A0, HIGH);
delay(150);
digitalWrite(A0, LOW);
digitalWrite(13, HIGH);
delay(150);
digitalWrite(13, LOW);
digitalWrite(12, HIGH);
delay(150);
digitalWrite(12, LOW);
digitalWrite(11, HIGH);
delay(150);
digitalWrite(11, LOW);
digitalWrite(10, HIGH);
delay(150);
digitalWrite(10, LOW);
digitalWrite(9, HIGH);
delay(150);
digitalWrite(9, LOW);
digitalWrite(8, HIGH);
delay(150);
digitalWrite(8, LOW);
digitalWrite(7, HIGH);
delay(150);
digitalWrite(7, LOW);
digitalWrite(6, HIGH);
delay(150);
digitalWrite(6, LOW);
digitalWrite(5, HIGH);
delay(150);
digitalWrite(5, LOW);
digitalWrite(4, HIGH);
delay(150);
digitalWrite(4, LOW);
digitalWrite(3, HIGH);
delay(150);
digitalWrite(3, LOW);
digitalWrite(2, HIGH);
delay(150);
digitalWrite(2, LOW);
//Knight Rider Effect
digitalWrite(2, HIGH);
delay(120);
digitalWrite(2, LOW);

digitalWrite(3, HIGH);
delay(120);
digitalWrite(3, LOW);
digitalWrite(4, HIGH);
delay(120);
digitalWrite(4, LOW);
digitalWrite(5, HIGH);
delay(120);
digitalWrite(5, LOW);
digitalWrite(6, HIGH);
delay(120);
digitalWrite(6, LOW);
digitalWrite(7, HIGH);
delay(120);
digitalWrite(7, LOW);
digitalWrite(8, HIGH);
delay(120);
digitalWrite(8, LOW);
digitalWrite(9, HIGH);
delay(120);
digitalWrite(9, LOW);
digitalWrite(10, HIGH);
delay(120);
digitalWrite(10, LOW);
digitalWrite(11, HIGH);
delay(120);
digitalWrite(11, LOW);
digitalWrite(12, HIGH);
delay(120);
digitalWrite(12, LOW);
digitalWrite(13, HIGH);
delay(120);
digitalWrite(13, LOW);
digitalWrite(A0, HIGH);
delay(120);
digitalWrite(A0, LOW);
digitalWrite(A1, HIGH);
delay(120);
digitalWrite(A1, LOW);
digitalWrite(A2, HIGH);
delay(120);
digitalWrite(A2, LOW);
digitalWrite(A1, HIGH);
delay(120);
digitalWrite(A1, LOW);
digitalWrite(A0, HIGH);
delay(120);
digitalWrite(A0, LOW);
digitalWrite(13, HIGH);
delay(120);
digitalWrite(13, LOW);
digitalWrite(12, HIGH);
delay(120);
digitalWrite(12, LOW);
digitalWrite(11, HIGH);
delay(120);
digitalWrite(11, LOW);
digitalWrite(10, HIGH);
delay(120);
digitalWrite(10, LOW);
digitalWrite(9, HIGH);
delay(120);
digitalWrite(9, LOW);
digitalWrite(8, HIGH);
delay(120);
digitalWrite(8, LOW);
digitalWrite(7, HIGH);
delay(120);
digitalWrite(7, LOW);
digitalWrite(6, HIGH);
delay(120);
digitalWrite(6, LOW);
digitalWrite(5, HIGH);
delay(120);
digitalWrite(5, LOW);
digitalWrite(4, HIGH);
delay(120);
digitalWrite(4, LOW);
digitalWrite(3, HIGH);
delay(120);
digitalWrite(3, LOW);
//Wave Effect
digitalWrite(2, HIGH);
digitalWrite(3, HIGH);
delay(200);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, HIGH);
digitalWrite(5, HIGH);
delay(200);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(6, HIGH);
digitalWrite(7, HIGH);
delay(200);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(8, HIGH);
digitalWrite(9, HIGH);
delay(200);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(10, HIGH);
digitalWrite(11, HIGH);
delay(200);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(12, HIGH);
digitalWrite(13, HIGH);
delay(200);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(A0, HIGH);
digitalWrite(A1, HIGH);
delay(200);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(A2, HIGH);
delay(300);
digitalWrite(A2, LOW);
digitalWrite(A0, HIGH);
digitalWrite(A1, HIGH);
delay(200);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(12, HIGH);
digitalWrite(13, HIGH);
delay(200);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(10, HIGH);
digitalWrite(11, HIGH);
delay(200);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(8, HIGH);
digitalWrite(9, HIGH);
delay(200);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(6, HIGH);
digitalWrite(7, HIGH);
delay(200);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(4, HIGH);
digitalWrite(5, HIGH);
delay(200);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(2, HIGH);
digitalWrite(3, HIGH);
delay(200);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
//Random Blink Effect
digitalWrite(7, HIGH);
delay(200);
digitalWrite(7, LOW);
digitalWrite(A1, HIGH);
delay(200);
digitalWrite(A1, LOW);
digitalWrite(3, HIGH);
delay(200);
digitalWrite(3, LOW);
digitalWrite(11, HIGH);
delay(200);
digitalWrite(11, LOW);
digitalWrite(5, HIGH);
delay(200);
digitalWrite(5, LOW);
digitalWrite(A2, HIGH);
delay(200);
digitalWrite(A2, LOW);
digitalWrite(9, HIGH);
delay(200);
digitalWrite(9, LOW);
digitalWrite(2, HIGH);
delay(200);
digitalWrite(2, LOW);
digitalWrite(13, HIGH);
delay(200);
digitalWrite(13, LOW);
digitalWrite(6, HIGH);
delay(200);
digitalWrite(6, LOW);
digitalWrite(A0, HIGH);
delay(200);
digitalWrite(A0, LOW);
digitalWrite(10, HIGH);
delay(200);
digitalWrite(10, LOW);
digitalWrite(4, HIGH);
delay(200);
digitalWrite(4, LOW);
digitalWrite(12, HIGH);
delay(200);
digitalWrite(12, LOW);
digitalWrite(8, HIGH);
delay(200);
digitalWrite(8, LOW);   
//Snake Effect
digitalWrite(2, HIGH);
delay(120);
digitalWrite(3, HIGH);
delay(120);
digitalWrite(2, LOW);
digitalWrite(4, HIGH);
delay(120);
digitalWrite(3, LOW);
digitalWrite(5, HIGH);
delay(120);
digitalWrite(4, LOW);
digitalWrite(6, HIGH);
delay(120);
digitalWrite(5, LOW);
digitalWrite(7, HIGH);
delay(120);
digitalWrite(6, LOW);
digitalWrite(8, HIGH);
delay(120);
digitalWrite(7, LOW);
digitalWrite(9, HIGH);
delay(120);
digitalWrite(8, LOW);
digitalWrite(10, HIGH);
delay(120);
digitalWrite(9, LOW);
digitalWrite(11, HIGH);
delay(120);
digitalWrite(10, LOW);
digitalWrite(12, HIGH);
delay(120);
digitalWrite(11, LOW);
digitalWrite(13, HIGH);
delay(120);
digitalWrite(12, LOW);
digitalWrite(A0, HIGH);
delay(120);
digitalWrite(13, LOW);
digitalWrite(A1, HIGH);
delay(120);
digitalWrite(A0, LOW);
digitalWrite(A2, HIGH);
delay(120);
digitalWrite(A1, LOW);
delay(300);
digitalWrite(A2, LOW);   
//Ripple Effect
digitalWrite(8, HIGH);
delay(150);
digitalWrite(7, HIGH);
digitalWrite(9, HIGH);
delay(150);
digitalWrite(6, HIGH);
digitalWrite(10, HIGH);
delay(150);
digitalWrite(5, HIGH);
digitalWrite(11, HIGH);
delay(150);
digitalWrite(4, HIGH);
digitalWrite(12, HIGH);
delay(150);
digitalWrite(3, HIGH);
digitalWrite(13, HIGH);
delay(150);
digitalWrite(2, HIGH);
digitalWrite(A0, HIGH);
delay(150);
digitalWrite(A1, HIGH);
delay(150);
digitalWrite(A2, HIGH);
delay(500);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(A2, LOW);
delay(300);
//Chase Effect
digitalWrite(2, HIGH);
digitalWrite(3, HIGH);
delay(150);
digitalWrite(2, LOW);
digitalWrite(4, HIGH);
delay(150);
digitalWrite(3, LOW);
digitalWrite(5, HIGH);
delay(150);
digitalWrite(4, LOW);
digitalWrite(6, HIGH);
delay(150);
digitalWrite(5, LOW);
digitalWrite(7, HIGH);
delay(150);
digitalWrite(6, LOW);
digitalWrite(8, HIGH);
delay(150);
digitalWrite(7, LOW);
digitalWrite(9, HIGH);
delay(150);
digitalWrite(8, LOW);
digitalWrite(10, HIGH);
delay(150);
digitalWrite(9, LOW);
digitalWrite(11, HIGH);
delay(150);
digitalWrite(10, LOW);
digitalWrite(12, HIGH);
delay(150);
digitalWrite(11, LOW);
digitalWrite(13, HIGH);
delay(150);
digitalWrite(12, LOW);
digitalWrite(A0, HIGH);
delay(150);
digitalWrite(13, LOW);
digitalWrite(A1, HIGH);
delay(150);
digitalWrite(A0, LOW);
digitalWrite(A2, HIGH);
delay(150);
digitalWrite(A1, LOW);
delay(200);
digitalWrite(A2, LOW);  
//Twinkle Effect
digitalWrite(2, HIGH);
delay(100);
digitalWrite(2, LOW);
digitalWrite(8, HIGH);
delay(100);
digitalWrite(8, LOW);
digitalWrite(A1, HIGH);
delay(100);
digitalWrite(A1, LOW);
digitalWrite(5, HIGH);
delay(100);
digitalWrite(5, LOW);
digitalWrite(11, HIGH);
delay(100);
digitalWrite(11, LOW);
digitalWrite(3, HIGH);
delay(100);
digitalWrite(3, LOW);
digitalWrite(A2, HIGH);
delay(100);
digitalWrite(A2, LOW);
digitalWrite(9, HIGH);
delay(100);
digitalWrite(9, LOW);
digitalWrite(6, HIGH);
delay(100);
digitalWrite(6, LOW);
digitalWrite(13, HIGH);
delay(100);
digitalWrite(13, LOW);
digitalWrite(4, HIGH);
delay(100);
digitalWrite(4, LOW);
digitalWrite(A0, HIGH);
delay(100);
digitalWrite(A0, LOW);
digitalWrite(10, HIGH);
delay(100);
digitalWrite(10, LOW);
digitalWrite(7, HIGH);
delay(100);
digitalWrite(7, LOW);
digitalWrite(12, HIGH);
delay(100);
digitalWrite(12, LOW);  
//Fireworks Effect
digitalWrite(8, HIGH);
delay(100);
digitalWrite(7, HIGH);
digitalWrite(9, HIGH);
delay(100);
digitalWrite(6, HIGH);
digitalWrite(10, HIGH);
delay(100);
digitalWrite(5, HIGH);
digitalWrite(11, HIGH);
delay(100);
digitalWrite(4, HIGH);
digitalWrite(12, HIGH);
delay(100);
digitalWrite(3, HIGH);
digitalWrite(13, HIGH);
delay(100);
digitalWrite(2, HIGH);
digitalWrite(A0, HIGH);
delay(100);
digitalWrite(A1, HIGH);
delay(100);
digitalWrite(A2, HIGH);
delay(500);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(A2, LOW);
delay(300);
digitalWrite(2, HIGH);
digitalWrite(5, HIGH);
digitalWrite(8, HIGH);
digitalWrite(11, HIGH);
digitalWrite(A2, HIGH);
delay(200);
digitalWrite(2, LOW);
digitalWrite(5, LOW);
digitalWrite(8, LOW);
digitalWrite(11, LOW);
digitalWrite(A2, LOW);
delay(200);   
//Heartbeat Effect
digitalWrite(2, HIGH);
digitalWrite(3, HIGH);
digitalWrite(4, HIGH);
digitalWrite(5, HIGH);
digitalWrite(6, HIGH);
digitalWrite(7, HIGH);
digitalWrite(8, HIGH);
digitalWrite(9, HIGH);
digitalWrite(10, HIGH);
digitalWrite(11, HIGH);
digitalWrite(12, HIGH);
digitalWrite(13, HIGH);
digitalWrite(A0, HIGH);
digitalWrite(A1, HIGH);
digitalWrite(A2, HIGH);
delay(150);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(A2, LOW);
delay(120);
digitalWrite(2, HIGH);
digitalWrite(3, HIGH);
digitalWrite(4, HIGH);
digitalWrite(5, HIGH);
digitalWrite(6, HIGH);
digitalWrite(7, HIGH);
digitalWrite(8, HIGH);
digitalWrite(9, HIGH);
digitalWrite(10, HIGH);
digitalWrite(11, HIGH);
digitalWrite(12, HIGH);
digitalWrite(13, HIGH);
digitalWrite(A0, HIGH);
digitalWrite(A1, HIGH);
digitalWrite(A2, HIGH);
delay(350);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(A2, LOW);
delay(600);  
//Rain Effect
digitalWrite(A2, HIGH);
delay(80);
digitalWrite(A2, LOW);
digitalWrite(A1, HIGH);
delay(80);
digitalWrite(A1, LOW);
digitalWrite(A0, HIGH);
delay(80);
digitalWrite(A0, LOW);
digitalWrite(13, HIGH);
delay(80);
digitalWrite(13, LOW);
digitalWrite(12, HIGH);
delay(80);
digitalWrite(12, LOW);
digitalWrite(11, HIGH);
delay(80);
digitalWrite(11, LOW);
digitalWrite(10, HIGH);
delay(80);
digitalWrite(10, LOW);
digitalWrite(9, HIGH);
delay(80);
digitalWrite(9, LOW);
digitalWrite(8, HIGH);
delay(80);
digitalWrite(8, LOW);
digitalWrite(7, HIGH);
delay(80);
digitalWrite(7, LOW);
digitalWrite(6, HIGH);
delay(80);
digitalWrite(6, LOW);
digitalWrite(5, HIGH);
delay(80);
digitalWrite(5, LOW);
digitalWrite(4, HIGH);
delay(80);
digitalWrite(4, LOW);
digitalWrite(3, HIGH);
delay(80);
digitalWrite(3, LOW);
digitalWrite(2, HIGH);
delay(80);
digitalWrite(2, LOW);
delay(300);   
//Meteor Shower Effect
digitalWrite(2, HIGH);
delay(80);
digitalWrite(3, HIGH);
delay(80);
digitalWrite(2, LOW);
digitalWrite(4, HIGH);
delay(80);
digitalWrite(3, LOW);
digitalWrite(5, HIGH);
delay(80);
digitalWrite(4, LOW);
digitalWrite(6, HIGH);
delay(80);
digitalWrite(5, LOW);
digitalWrite(7, HIGH);
delay(80);
digitalWrite(6, LOW);
digitalWrite(8, HIGH);
delay(80);
digitalWrite(7, LOW);
digitalWrite(9, HIGH);
delay(80);
digitalWrite(8, LOW);
digitalWrite(10, HIGH);
delay(80);
digitalWrite(9, LOW);
digitalWrite(11, HIGH);
delay(80);
digitalWrite(10, LOW);
digitalWrite(12, HIGH);
delay(80);
digitalWrite(11, LOW);
digitalWrite(13, HIGH);
delay(80);
digitalWrite(12, LOW);
digitalWrite(A0, HIGH);
delay(80);
digitalWrite(13, LOW);
digitalWrite(A1, HIGH);
delay(80);
digitalWrite(A0, LOW);
digitalWrite(A2, HIGH);
delay(80);
digitalWrite(A1, LOW);
delay(200);
digitalWrite(A2, LOW);
delay(300);
//Explosion Effect

digitalWrite(8, HIGH);
delay(100);

digitalWrite(7, HIGH);
digitalWrite(9, HIGH);
delay(100);

digitalWrite(6, HIGH);
digitalWrite(10, HIGH);
delay(100);

digitalWrite(5, HIGH);
digitalWrite(11, HIGH);
delay(100);

digitalWrite(4, HIGH);
digitalWrite(12, HIGH);
delay(100);

digitalWrite(3, HIGH);
digitalWrite(13, HIGH);
delay(100);

digitalWrite(2, HIGH);
digitalWrite(A0, HIGH);
delay(100);

digitalWrite(A1, HIGH);
delay(100);

digitalWrite(A2, HIGH);
delay(300);

//Flash
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(A2, LOW);

delay(100);

digitalWrite(8, HIGH);
digitalWrite(7, HIGH);
digitalWrite(9, HIGH);
digitalWrite(6, HIGH);
digitalWrite(10, HIGH);
digitalWrite(5, HIGH);
digitalWrite(11, HIGH);
digitalWrite(4, HIGH);
digitalWrite(12, HIGH);
digitalWrite(3, HIGH);
digitalWrite(13, HIGH);
digitalWrite(2, HIGH);
digitalWrite(A0, HIGH);
digitalWrite(A1, HIGH);
digitalWrite(A2, HIGH);

delay(50);
digitalWrite(2, LOW);
digitalWrite(3, LOW);
digitalWrite(4, LOW);
digitalWrite(5, LOW);
digitalWrite(6, LOW);
digitalWrite(7, LOW);
digitalWrite(8, LOW);
digitalWrite(9, LOW);
digitalWrite(10, LOW);
digitalWrite(11, LOW);
digitalWrite(12, LOW);
digitalWrite(13, LOW);
digitalWrite(A0, LOW);
digitalWrite(A1, LOW);
digitalWrite(A2, LOW);
delay(500);
  
}
